version: '3.2'

services:
  web:
    build: .
    depends_on:
      - redis
    command: gunicorn server:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - "8080:8080"
  redis:
    image: redis
